kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: <APP_NAME>
  name: <APP_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <APP_NAME>
  template:
    metadata:
      labels:
        app: <APP_NAME>
    spec:
      containers:
        - name: <APP_NAME>
          image: <NEXUS_HOST>/<DOCKER_IMAGE>:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      nodeSelector:
        kubernetes.io/hostname: node02
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <APP_NAME>
apiVersion: v1
kind: Service
metadata:
  labels:
    app: <APP_NAME>
  name: <APP_NAME>
spec:
  type: NodePort
  ports:
    - port: 5010
      targetPort: 5010
      nodePort: 30085
      name: <APP_NAME>
  selector:
    app: <APP_NAME>